
package com.databasserne.loanbroker.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RulesServiceService", targetNamespace = "http://webservices.loanbroker.databasserne.com/", wsdlLocation = "http://localhost:9999/rules/banks?wsdl")
public class RulesServiceService
    extends Service
{

    private final static URL RULESSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException RULESSERVICESERVICE_EXCEPTION;
    private final static QName RULESSERVICESERVICE_QNAME = new QName("http://webservices.loanbroker.databasserne.com/", "RulesServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/rules/banks?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RULESSERVICESERVICE_WSDL_LOCATION = url;
        RULESSERVICESERVICE_EXCEPTION = e;
    }

    public RulesServiceService() {
        super(__getWsdlLocation(), RULESSERVICESERVICE_QNAME);
    }

    public RulesServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RULESSERVICESERVICE_QNAME, features);
    }

    public RulesServiceService(URL wsdlLocation) {
        super(wsdlLocation, RULESSERVICESERVICE_QNAME);
    }

    public RulesServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RULESSERVICESERVICE_QNAME, features);
    }

    public RulesServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RulesServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RulesService
     */
    @WebEndpoint(name = "RulesServicePort")
    public RulesService getRulesServicePort() {
        return super.getPort(new QName("http://webservices.loanbroker.databasserne.com/", "RulesServicePort"), RulesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RulesService
     */
    @WebEndpoint(name = "RulesServicePort")
    public RulesService getRulesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.loanbroker.databasserne.com/", "RulesServicePort"), RulesService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RULESSERVICESERVICE_EXCEPTION!= null) {
            throw RULESSERVICESERVICE_EXCEPTION;
        }
        return RULESSERVICESERVICE_WSDL_LOCATION;
    }

}
