
package com.databasserne.loanbroker.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RulesService", targetNamespace = "http://webservices.loanbroker.databasserne.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RulesService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBanks", targetNamespace = "http://webservices.loanbroker.databasserne.com/", className = "com.databasserne.loanbroker.webservices.GetBanks")
    @ResponseWrapper(localName = "getBanksResponse", targetNamespace = "http://webservices.loanbroker.databasserne.com/", className = "com.databasserne.loanbroker.webservices.GetBanksResponse")
    @Action(input = "http://webservices.loanbroker.databasserne.com/RulesService/getBanksRequest", output = "http://webservices.loanbroker.databasserne.com/RulesService/getBanksResponse")
    public String getBanks(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
